-- Run this in the Supabase SQL Editor

-- 1. Create the attendance table
create table attendance (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  date text not null,      -- Format: YYYY-MM-DD
  time text not null,      -- Format: HH:MM
  staff text not null,     -- Staff Name
  action text not null,    -- "出勤", "退勤", etc.
  timestamp text           -- ISO String from JS (optional backup)
);

-- 2. Enable Realtime (so staff status updates instantly)
alter publication supabase_realtime add table attendance;

-- 3. (Optional) Disable Row Level Security (RLS) for simple usage
-- If you want anyone with the Key to be able to read/write (easiest for this use case)
alter table attendance disable row level security;
